- name: 'ubuntu | install prerequisite packages'
  apt:
    name: "{{ item.package }}"
    state: present
  with_items: "{{ docker_prerequisite_packages }}"
  become: yes

- name: 'ubuntu | import docker ce repository gpg key without proxy'
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/ubuntu/gpg', split_lines=False) }}"
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  when: os_proxy is undefined
  become: yes

- name: 'ubuntu | import docker ce repository gpg key using proxy'
  environment:
    http_proxy: "{{ os_proxy }}"
    https_proxy: "{{ os_proxy }}"
  apt_key:
    data: "{{ lookup('url', 'https://download.docker.com/linux/ubuntu/gpg', split_lines=False) }}"
    state: present
    id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
  when: os_proxy is defined
  become: yes

- name: 'ubuntu | add docker ce repository'
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  become: yes

- name: 'ubuntu | install docker ce'
  apt:
    name: "{{  docker_packages_debian }}"
    state: present
    update_cache: yes
  become: yes
