---
- name: 'restart docker'
  become: yes
  service:
    name: 'docker'
    state: 'restarted'

- name: 'reload systemd'
  become: yes
  systemd:
    name: 'docker.service'
    state: restarted
    daemon_reload: yes

- name: 'systemd start docker-cleanup'
  systemd:
    name: '{{ docker_cleanup_file }}.timer'
    state: started
    daemon_reload: yes
  become: yes
